/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/health": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Health
     * @description Liveness + DB ping. Returns 200 with `db: "ok"` on a working stack.
     */
    get: operations["health_health_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/atoms": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Atoms */
    get: operations["list_atoms_atoms_get"];
    put?: never;
    /** Create Atom */
    post: operations["create_atom_atoms_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/atoms/{atom_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Atom */
    get: operations["get_atom_atoms__atom_id__get"];
    put?: never;
    post?: never;
    /** Delete Atom */
    delete: operations["delete_atom_atoms__atom_id__delete"];
    options?: never;
    head?: never;
    /** Update Atom */
    patch: operations["update_atom_atoms__atom_id__patch"];
    trace?: never;
  };
  "/persons": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Persons */
    get: operations["list_persons_persons_get"];
    put?: never;
    /** Create Person */
    post: operations["create_person_persons_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/persons/{person_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Person */
    get: operations["get_person_persons__person_id__get"];
    put?: never;
    post?: never;
    /** Delete Person */
    delete: operations["delete_person_persons__person_id__delete"];
    options?: never;
    head?: never;
    /** Update Person */
    patch: operations["update_person_persons__person_id__patch"];
    trace?: never;
  };
  "/meetings": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Meetings */
    get: operations["list_meetings_meetings_get"];
    put?: never;
    /** Create Meeting */
    post: operations["create_meeting_meetings_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/meetings/{meeting_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Meeting */
    get: operations["get_meeting_meetings__meeting_id__get"];
    put?: never;
    post?: never;
    /** Delete Meeting */
    delete: operations["delete_meeting_meetings__meeting_id__delete"];
    options?: never;
    head?: never;
    /** Update Meeting */
    patch: operations["update_meeting_meetings__meeting_id__patch"];
    trace?: never;
  };
  "/projects": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Projects */
    get: operations["list_projects_projects_get"];
    put?: never;
    /** Create Project */
    post: operations["create_project_projects_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/projects/{project_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Project */
    get: operations["get_project_projects__project_id__get"];
    put?: never;
    post?: never;
    /** Delete Project */
    delete: operations["delete_project_projects__project_id__delete"];
    options?: never;
    head?: never;
    /** Update Project */
    patch: operations["update_project_projects__project_id__patch"];
    trace?: never;
  };
  "/saved-filters": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Saved Filters */
    get: operations["list_saved_filters_saved_filters_get"];
    put?: never;
    /** Create Saved Filter */
    post: operations["create_saved_filter_saved_filters_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/saved-filters/{filter_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Saved Filter */
    get: operations["get_saved_filter_saved_filters__filter_id__get"];
    put?: never;
    post?: never;
    /** Delete Saved Filter */
    delete: operations["delete_saved_filter_saved_filters__filter_id__delete"];
    options?: never;
    head?: never;
    /** Update Saved Filter */
    patch: operations["update_saved_filter_saved_filters__filter_id__patch"];
    trace?: never;
  };
  "/views/inbox": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Inbox */
    get: operations["inbox_views_inbox_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Root */
    get: operations["root__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /** AtomCreate */
    AtomCreate: {
      /** Slug */
      slug: string;
      /**
       * Content
       * @default
       */
      content: string;
      /** Content Json */
      content_json?: {
        [key: string]: unknown;
      } | null;
      /**
       * Type
       * @default note
       * @enum {string}
       */
      type: "note" | "task" | "event" | "reminder" | "reference";
      /**
       * Status
       * @default open
       * @enum {string}
       */
      status: "open" | "in_progress" | "done" | "cancelled" | "waiting";
      /**
       * Priority
       * @default medium
       * @enum {string}
       */
      priority: "low" | "medium" | "high" | "urgent";
      /**
       * Inbox
       * @default true
       */
      inbox: boolean;
      /** Reminder */
      reminder?: string | null;
      /** Deadline */
      deadline?: string | null;
      /**
       * Deadline Hard
       * @default false
       */
      deadline_hard: boolean;
      /** Project Id */
      project_id?: string | null;
      /** Meeting Id */
      meeting_id?: string | null;
      /** Assigned To */
      assigned_to?: string | null;
      /**
       * Person Ids
       * @default []
       */
      person_ids: string[];
    };
    /** AtomRead */
    AtomRead: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Slug */
      slug: string;
      /** Content */
      content: string;
      /** Content Json */
      content_json: {
        [key: string]: unknown;
      } | null;
      /** Type */
      type: string;
      /** Status */
      status: string;
      /** Priority */
      priority: string;
      /** Inbox */
      inbox: boolean;
      /** Reminder */
      reminder: string | null;
      /** Deadline */
      deadline: string | null;
      /** Deadline Hard */
      deadline_hard: boolean;
      /** Project Id */
      project_id: string | null;
      /** Meeting Id */
      meeting_id: string | null;
      /** Assigned To */
      assigned_to: string | null;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /**
       * Updated At
       * Format: date-time
       */
      updated_at: string;
      /** Deleted At */
      deleted_at: string | null;
    };
    /** AtomUpdate */
    AtomUpdate: {
      /** Content */
      content?: string | null;
      /** Content Json */
      content_json?: {
        [key: string]: unknown;
      } | null;
      /** Type */
      type?: ("note" | "task" | "event" | "reminder" | "reference") | null;
      /** Status */
      status?: ("open" | "in_progress" | "done" | "cancelled" | "waiting") | null;
      /** Priority */
      priority?: ("low" | "medium" | "high" | "urgent") | null;
      /** Inbox */
      inbox?: boolean | null;
      /** Reminder */
      reminder?: string | null;
      /** Deadline */
      deadline?: string | null;
      /** Deadline Hard */
      deadline_hard?: boolean | null;
      /** Project Id */
      project_id?: string | null;
      /** Meeting Id */
      meeting_id?: string | null;
      /** Assigned To */
      assigned_to?: string | null;
      /** Person Ids */
      person_ids?: string[] | null;
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components["schemas"]["ValidationError"][];
    };
    /** MeetingCreate */
    MeetingCreate: {
      /** Slug */
      slug: string;
      /** Title */
      title: string;
      /** Date */
      date?: string | null;
      /** Notes */
      notes?: string | null;
      /** Project Id */
      project_id?: string | null;
      /**
       * Participant Ids
       * @default []
       */
      participant_ids: string[];
    };
    /** MeetingRead */
    MeetingRead: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Slug */
      slug: string;
      /** Title */
      title: string;
      /** Date */
      date: string | null;
      /** Notes */
      notes: string | null;
      /** Project Id */
      project_id: string | null;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /**
       * Updated At
       * Format: date-time
       */
      updated_at: string;
      /** Deleted At */
      deleted_at: string | null;
    };
    /** MeetingUpdate */
    MeetingUpdate: {
      /** Title */
      title?: string | null;
      /** Date */
      date?: string | null;
      /** Notes */
      notes?: string | null;
      /** Project Id */
      project_id?: string | null;
      /** Participant Ids */
      participant_ids?: string[] | null;
    };
    /** PersonCreate */
    PersonCreate: {
      /** Slug */
      slug: string;
      /** Name */
      name: string;
      /** Email */
      email?: string | null;
      /** Notes */
      notes?: string | null;
    };
    /** PersonRead */
    PersonRead: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Slug */
      slug: string;
      /** Name */
      name: string;
      /** Email */
      email: string | null;
      /** Notes */
      notes: string | null;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /**
       * Updated At
       * Format: date-time
       */
      updated_at: string;
      /** Deleted At */
      deleted_at: string | null;
    };
    /** PersonUpdate */
    PersonUpdate: {
      /** Name */
      name?: string | null;
      /** Email */
      email?: string | null;
      /** Notes */
      notes?: string | null;
    };
    /** ProjectCreate */
    ProjectCreate: {
      /** Slug */
      slug: string;
      /** Name */
      name: string;
      /** Description */
      description?: string | null;
      /**
       * Status
       * @default active
       * @enum {string}
       */
      status: "active" | "on_hold" | "completed" | "cancelled";
    };
    /** ProjectRead */
    ProjectRead: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Slug */
      slug: string;
      /** Name */
      name: string;
      /** Description */
      description: string | null;
      /** Status */
      status: string;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /**
       * Updated At
       * Format: date-time
       */
      updated_at: string;
      /** Deleted At */
      deleted_at: string | null;
    };
    /** ProjectUpdate */
    ProjectUpdate: {
      /** Name */
      name?: string | null;
      /** Description */
      description?: string | null;
      /** Status */
      status?: ("active" | "on_hold" | "completed" | "cancelled") | null;
    };
    /** SavedFilterCreate */
    SavedFilterCreate: {
      /** Slug */
      slug: string;
      /** Name */
      name: string;
      /**
       * Filter Json
       * @default {}
       */
      filter_json: {
        [key: string]: unknown;
      };
    };
    /** SavedFilterRead */
    SavedFilterRead: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Slug */
      slug: string;
      /** Name */
      name: string;
      /** Filter Json */
      filter_json: {
        [key: string]: unknown;
      };
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /**
       * Updated At
       * Format: date-time
       */
      updated_at: string;
      /** Deleted At */
      deleted_at: string | null;
    };
    /** SavedFilterUpdate */
    SavedFilterUpdate: {
      /** Name */
      name?: string | null;
      /** Filter Json */
      filter_json?: {
        [key: string]: unknown;
      } | null;
    };
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
      /** Input */
      input?: unknown;
      /** Context */
      ctx?: Record<string, never>;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  health_health_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
    };
  };
  list_atoms_atoms_get: {
    parameters: {
      query?: {
        /** @description Fulltext search */
        q?: string | null;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AtomRead"][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  create_atom_atoms_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["AtomCreate"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AtomRead"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_atom_atoms__atom_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        atom_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AtomRead"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  delete_atom_atoms__atom_id__delete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        atom_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  update_atom_atoms__atom_id__patch: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        atom_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["AtomUpdate"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AtomRead"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  list_persons_persons_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PersonRead"][];
        };
      };
    };
  };
  create_person_persons_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["PersonCreate"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PersonRead"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_person_persons__person_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        person_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PersonRead"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  delete_person_persons__person_id__delete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        person_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  update_person_persons__person_id__patch: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        person_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["PersonUpdate"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PersonRead"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  list_meetings_meetings_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["MeetingRead"][];
        };
      };
    };
  };
  create_meeting_meetings_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["MeetingCreate"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["MeetingRead"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_meeting_meetings__meeting_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        meeting_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["MeetingRead"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  delete_meeting_meetings__meeting_id__delete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        meeting_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  update_meeting_meetings__meeting_id__patch: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        meeting_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["MeetingUpdate"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["MeetingRead"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  list_projects_projects_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProjectRead"][];
        };
      };
    };
  };
  create_project_projects_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ProjectCreate"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProjectRead"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_project_projects__project_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        project_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProjectRead"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  delete_project_projects__project_id__delete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        project_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  update_project_projects__project_id__patch: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        project_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ProjectUpdate"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProjectRead"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  list_saved_filters_saved_filters_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SavedFilterRead"][];
        };
      };
    };
  };
  create_saved_filter_saved_filters_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["SavedFilterCreate"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SavedFilterRead"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_saved_filter_saved_filters__filter_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        filter_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SavedFilterRead"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  delete_saved_filter_saved_filters__filter_id__delete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        filter_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  update_saved_filter_saved_filters__filter_id__patch: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        filter_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["SavedFilterUpdate"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SavedFilterRead"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  inbox_views_inbox_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AtomRead"][];
        };
      };
    };
  };
  root__get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: string;
          };
        };
      };
    };
  };
}
